name: Update Module Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'modules/**/*.tf'
      - 'modules/**/README.md'
      - '.github/workflows/docs.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'modules/**/*.tf'
      - 'modules/**/README.md'
      - '.github/workflows/docs.yml'

jobs:
  generate-docs:
    name: Generate Terraform Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: modules/vnet
          output-file: README.md
          output-method: inject
          git-push: "true"
          
  validate-docs:
    name: Validate Documentation
    runs-on: ubuntu-latest
    needs: [generate-docs]
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check README Completeness
        run: |
          echo "Validating module documentation completeness..."
          
          # Check if the VNet module has a README.md
          if [ ! -f "modules/vnet/README.md" ]; then
            echo "ERROR: modules/vnet/README.md is missing!"
            exit 1
          fi
          
          # Check if the README has minimum required sections
          README_CONTENT=$(cat modules/vnet/README.md)
          
          if ! echo "$README_CONTENT" | grep -q "## Requirements"; then
            echo "WARNING: README.md is missing Requirements section"
          fi
          
          if ! echo "$README_CONTENT" | grep -q "## Providers"; then
            echo "WARNING: README.md is missing Providers section"
          fi
          
          if ! echo "$README_CONTENT" | grep -q "## Inputs"; then
            echo "WARNING: README.md is missing Inputs section"
          fi
          
          if ! echo "$README_CONTENT" | grep -q "## Outputs"; then
            echo "WARNING: README.md is missing Outputs section"
          fi
          
          echo "Documentation validation completed!" 